//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QuanLySinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblviwSystemSecurityUserAttribute
    {
        public int User_ID { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public int ID { get; set; }
        public Nullable<int> Privilege_ID { get; set; }
        public Nullable<int> AccessPermission { get; set; }
    }
}
