'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace DAL_QuanLySinhVien

    Partial Public Class QuanLySinhVienEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=QuanLySinhVienEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property ChuyenNganhs() As DbSet(Of ChuyenNganh)
        Public Overridable Property DangKyMonHocs() As DbSet(Of DangKyMonHoc)
        Public Overridable Property MonHocs() As DbSet(Of MonHoc)
        Public Overridable Property SinhViens() As DbSet(Of SinhVien)
        Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    
    End Class

End Namespace
