//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QuanLySinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int MaSinhVien { get; set; }
        public string HoTen { get; set; }
        public Nullable<double> Diem { get; set; }
        public string GioiTinh { get; set; }
    }
}
